### ISSUE TITLE
an issue starting the rich presence in the new version

### ISSUE THREAD

**Issue by marwansaad1272** [XFG16/YouTubeDiscordPresence#1]
when I open the YTDPwin.exe it opens but a message like this pops up:Error: Could not connect
    at Socket.onerror (C:\snapshot\NodeHost\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:520:26)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
   {"data":"CLIENT_ERROR"}

**Comment by XFG16** [comment]
Sorry for late response!

You shouldn't be opening the executable file manually. It will be automatically launched by the extension itself, which will handle any issues like the one you have.
